import Head from 'next/head'
import Link from 'next/link';
import { homePagePath } from '../home/homePageMeta';

export interface LoginPageProps {
}

export const LoginPage: React.FC<LoginPageProps> = (props) => {
  return (
    <div className="LoginPage">
      <Head>
        <title>LoginPage</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>LoginPage</h1>
      <p>
        <Link href={homePagePath()}>Home</Link>
      </p>
    </div>
  );
};
