import Head from 'next/head'
import Link from 'next/link';
import { loginPagePath } from '../login/loginPageMeta';

export interface HomePageProps {
}

export const HomePage: React.FC<HomePageProps> = (props) => {
  return (
    <div className="HomePage">
      <Head>
        <title>HomePage</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>HomePage</h1>
      <p>
        <Link href={loginPagePath()}>Login</Link>
      </p>
    </div>
  );
};
