import Head from "next/head";
import Link from "next/link";
import { BasicLayout } from "@login-app/ui";
import { loginPagePath } from "../login/loginPageMeta";

export interface HomePageProps {}

export const HomePage: React.FC<HomePageProps> = (props) => {
  return (
    <BasicLayout title="HomePage">
      <Head>
        <title>HomePage</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>HomePage</h1>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>
      <p>
        <Link href={loginPagePath()}>Login</Link>
      </p>
    </BasicLayout>
  );
};
